### ISSUE TITLE
Issue with re-sending pending jobs

### ISSUE THREAD

**Issue by noggan** [interactive-solutions/go-communication#1]
When we re-queue all pending jobs as following:

```go
for _, job := range jobs {
	app.queue(&job)
}
```

we create a reference issue because we send a reference to a stack variable that updates each
loop iteration. This may lead to the same email being sent multiple times.

To resolve this issue we should do it like this:

```go
for _, job := range jobs {
	cpy := job

	app.queue(&cpy)
}
```

or something that is an equivalent change.

**Comment by awartoft** [comment]
Closed with d7102e60dd651273044098c89e894500a0409b5c
