### ISSUE TITLE
Parse HTML -> Text if TextBody is empty

### ISSUE THREAD

**Issue by jarnell** [interactive-solutions/go-communication#3]
Would be nice if this library would parse the HTML input to text if TextBody is omitted/empty. That way, you wouldn't have to enter both HtmlBody and TextBody for all templates, but would still have the option to control TextBody in special cases.

Perhaps this library can be used to parse HTML: https://github.com/jaytaylor/html2text
(please turn off prettyTables, though!)

**Comment by noggan** [comment]
Added option to specify a function that converts html body to text body if the provided text body is empty when updating a template.
